# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/c-cpp/gcc

pool:
  vmImage: 'Ubuntu 18.04'
  

steps:
- checkout:
  fetchDepth: 5
  
- script:
    make CPUS="2" PKGS="racket-test db-test unstable-flonum-lib net-test" CONFIGURE_ARGS_qq="$RACKET_CONFIGURE_ARGS"
  displayName: 'make'
  
- script: |
    export PATH=$PATH:`pwd`:/racket/bin
    raco test -l tests/racket/test
    racket -l tests/racket/contract/all
    raco test -l tests/json/json
    raco test -l tests/file/main
    raco test -l tests/net/head
    raco test -l tests/net/uri-codec
    raco test -l tests/net/url
    raco test -l tests/net/url-port
    raco test -l tests/net/encoders
    raco test -l tests/openssl/basic
    raco test -l tests/openssl/https
    raco test -l tests/match/main
    raco test -l tests/zo-path
    raco test -l tests/xml/test
    raco test -l tests/db/all-tests
    raco test -c tests/stxparse
  displayName: test
